 version: '3'

 services:
  
  studentapp:
    build:
      context: ./
      dockerfile: ./studentapp.dockerfile
    restart: always
    ports: 
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1